use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));

    let config_dir = Path::new(&manifest_dir).join("config").join("client");
    let generated = out_dir.join("official_templates_generated.rs");

    // Always rerun if directory changes or any file changes
    println!("cargo:rerun-if-changed={}", config_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if config_dir.exists() {
        for entry in walk(&config_dir) {
            if let Some(ext) = entry.extension().and_then(|s| s.to_str()) {
                let ext = ext.to_ascii_lowercase();
                if ["json", "json5", "yaml", "yml", "toml"].contains(&ext.as_str()) {
                    let file_name = entry
                        .file_name()
                        .and_then(|s| s.to_str())
                        .unwrap_or_default()
                        .to_string();
                    // path relative to manifest for include_str!
                    let rel = match entry.strip_prefix(&manifest_dir) {
                        Ok(p) => {
                            let s = p.to_string_lossy().to_string().replace('\\', "/");
                            format!("/{}", s)
                        }
                        Err(_) => format!("/config/client/{}", file_name),
                    };
                    // Add file-specific change tracking
                    println!("cargo:rerun-if-changed={}", entry.display());
                    entries.push((file_name, rel));
                }
            }
        }
    }

    // Sort for stable builds
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate Rust source
    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit\n");
    code.push_str("pub const OFFICIAL_TEMPLATES: &[(&str, &str)] = &[\n");
    for (file_name, rel) in entries {
        // Use env!("CARGO_MANIFEST_DIR") + relative path to make include_str! robust
        code.push_str(&format!(
            "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"{}\"))),\n",
            file_name, rel
        ));
    }
    code.push_str("];\n");

    // Write generated file
    fs::create_dir_all(&out_dir).expect("create OUT_DIR");
    let mut f = fs::File::create(&generated).expect("create generated file");
    f.write_all(code.as_bytes()).expect("write generated code");
}

fn walk(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(path) = stack.pop() {
        if let Ok(read_dir) = fs::read_dir(&path) {
            for entry in read_dir.flatten() {
                let p = entry.path();
                if p.is_dir() {
                    stack.push(p);
                } else {
                    files.push(p);
                }
            }
        }
    }
    files
}
